<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-E4HH55MS" failures="0" tests="2" name="testng.TimeOutTest" time="5.044" errors="1" timestamp="2022-11-01T08:22:32 PDT" skipped="0">
  <testcase classname="testng.TimeOutTest" name="secondTest" time="3.017">
    <error message="Method testng.TimeOutTest.secondTest() didn&#039;t finish within the time-out 3000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng.TimeOutTest.secondTest() didn't finish within the time-out 3000
at java.base@18.0.2.1/java.lang.Thread.sleep(Native Method)
at app//testng.TimeOutTest.secondTest(TimeOutTest.java:15)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d10c00.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.2.1/java.lang.invoke.LambdaForm$MH/0x0000000800d11400.invoke(LambdaForm$MH)
at java.base@18.0.2.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.2.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
at java.base@18.0.2.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base@18.0.2.1/java.lang.reflect.Method.invoke(Method.java:577)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@18.0.2.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.2.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- secondTest -->
  <system-out/>
  <testcase classname="testng.TimeOutTest" name="FirstTest" time="2.027"/>
  <system-out/>
</testsuite> <!-- testng.TimeOutTest -->
